# Generated by Django 5.0.2 on 2024-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biopic',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='defname', max_length=100),
            preserve_default=False,
        ),
    ]
